server {
        listen 9080  ssl;
        listen [::]:9080  ssl;
        include snippets/self-signed.conf;
        include snippets/ssl-params.conf;
        server_tokens off;

        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;
        server_name vps293665.vps.ovh.ca; # managed by Certbot

        location / {
                try_files $uri $uri/ =404;
        }

        # Covers without auth (for OPDS readers)
        location /cops/cover/ {
                auth_basic off;

                proxy_pass http://127.0.0.1:8080/cover/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
        }

        # Calibre OPDS/Web Server
        location /cops/ {
                auth_basic "Calibre Library";
                auth_basic_user_file /etc/nginx/contrasenas;

                proxy_pass http://127.0.0.1:8080/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~ /\.ht {
                deny all;
        }

    ssl_certificate /etc/letsencrypt/live/vps293665.vps.ovh.ca/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/vps293665.vps.ovh.ca/privkey.pem; # managed by Certbot
}
